[project]
name = "twilio-personalization-python"
version = "0.1.0"
description = "ElevenLabs Twilio Personalization Webhook - Python Implementation"
authors = [
    {name = "Demo"}
]
readme = "README.md"
requires-python = "^3.9"
dependencies = [
    "fastapi (>=0.115.6,<0.117.0)",
    "uvicorn[standard] (>=0.32.1,<0.36.0)",
    "pydantic (>=2.10.4,<3.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
